### ISSUE TITLE
Hey can you please explain how to run this code :)

### ISSUE THREAD

**Issue by StaticGamerYT-India** [scaredofseagles/mock-car-thing#1]
i am really exited to see this project but i am not sure how do i run this project
i tried looking into files but couldnt make out what to do 
please help me :)

**Comment by scaredofseagles** [comment]
Hi Smeet, I appreciate the interest in my project however it is very much still in progress 😔. But, I would be more than happy to answer any questions if you plan to create your version of this.

**Comment by StaticGamerYT-India** [comment]
woow that's great 
well i am trying to make a portfolio website currently but the errors are really frustrating
